stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end"
  CHROME_BIN: "/usr/bin/chromium"
  DISPLAY: ":99"

# Backend pipeline
backend_build:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - cd src/app/Backend
    - mvn clean package -DskipTests
    - echo "Backend installed"
  artifacts:
    paths:
      - src/app/Backend/target/*.jar

backend_test:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - cd src/app/Backend
    - mvn test

backend_deploy:
  stage: deploy
  image: openjdk:17-jdk-slim
  script:
    - java -jar src/app/Backend/target/*.jar
  only:
    - main

# Frontend pipeline
frontend_build:
  stage: build
  image: node:18-buster
  script:
    - ls -R
    - cd src/app/components
    - npm install
    - npm run build --prod
    - echo "Frontend installed"
  artifacts:
    paths:
      - dist

frontend_test:
  stage: test
  image: node:18-buster
  variables:
    PROJECT_DIR: /project
  script:
    # Création d'un utilisateur non-root
    - useradd -m testuser
    - export HOME=/home/testuser
    - mkdir -p $PROJECT_DIR
    - chown -R testuser:testuser $PROJECT_DIR

    # Préparation des fichiers du projet
    - mv * $PROJECT_DIR || true
    - cd $PROJECT_DIR

    # Installation de Chromium et configuration
    - apt-get update && apt-get upgrade -y && apt-get install -y chromium xvfb
    - if ! which chromium; then echo "Chromium n'est pas installé correctement !" && exit 1; fi
    - export CHROME_BIN=$(which chromium)  # Mise à jour dynamique de CHROME_BIN
    - export DISPLAY=:99
    - Xvfb :99 -ac &

    # Vérification de Chromium
    - chromium --version || { echo "Chromium n'a pas pu être lancé !" && exit 1; }

    # Installation et exécution des tests
    - echo "Exécution des tests front-end avec ChromeHeadless"
    - npm install --save-dev @angular/cli
    - npm ci
    - su - testuser -c "cd $PROJECT_DIR && npm test"

frontend_deploy:
  stage: deploy
  image: node:18-buster
  script:
    - cd dist
    - npx http-server -p 4200
  only:
    - main
