stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end"
  CHROME_BIN: "/usr/bin/chromium"  

  DISPLAY: ":99"  

# Backend pipeline
backend_build:
  stage: build
  image: maven:3.8-openjdk-17
  script: 
    - cd src/app/Backend
    - mvn clean package -DskipTests
    - echo "Backend installed"
  artifacts:
    paths:
      - src/app/Backend/target/*.jar

backend_test:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - cd src/app/Backend
    - mvn test

backend_deploy:
  stage: deploy
  image: openjdk:17-jdk-slim
  script:
    - java -jar src/app/Backend/target/*.jar
  only:
    - main

# Frontend pipeline
frontend_build:
  stage: build
  image: node:18-buster  
  script:
    - ls -R
    - cd src/app/components
    - npm install
    - npm run build --prod
    - echo "Frontend installed"
  artifacts:
    paths:
      - dist

frontend_test:
  stage: test
  image: node:18-buster
  script:
 
    # Créez un utilisateur non-root
    - useradd -m testuser
    - export HOME=/home/testuser 
    - chown -R testuser:testuser ./
    # Installez Chromium et Xvfb
    - apt-get update && apt-get install -y chromium xvfb
    - export CHROME_BIN=/usr/bin/chromium
    - export DISPLAY=:99
    - Xvfb :99 -ac &
    - echo "Exécution des tests front-end avec ChromeHeadless"
    - npm install --save-dev @angular/cli
    - npm install 
    # Exécutez les tests en tant qu'utilisateur non-root
    - ls -l /projet-pmt/package.json 
    - su - testuser -c "cd /build && npm test"



frontend_deploy:
  stage: deploy
  image: node:18-buster  
  script:
    - cd dist
    - npx http-server -p 4200
  only:
    - main