variables:
  GOOGLE_PROJECT_ID: "peak-lattice-447302-b9"
  GOOGLE_COMPUTE_ZONE: "europe-west1-b"
  SPRING_IMAGE_NAME: "gcr.io/${GOOGLE_PROJECT_ID}/spring-backend:${CI_COMMIT_SHA}"
  ANGULAR_IMAGE_NAME: "gcr.io/${GOOGLE_PROJECT_ID}/angular-frontend:${CI_COMMIT_SHA}"

stages:
  - build
  - test
  - docker
  - deploy

# Backend jobs
build-backend:
  stage: build
  image: maven:3.8.7-openjdk-18
  script:
    - cd src/app/Backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - src/app/Backend/target/*.jar

test-backend:
  stage: test
  image: maven:3.8.7-openjdk-18
  script:
    - cd src/app/Backend
    - mvn test -X
  artifacts:
    when: on_failure
    paths:
      - src/app/Backend/target/surefire-reports/


docker-backend:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo $GOOGLE_CLOUD_KEY > /tmp/google-cloud-key.json
    - gcloud auth activate-service-account --key-file /tmp/google-cloud-key.json
    - gcloud config set project $GOOGLE_PROJECT_ID
    - gcloud auth configure-docker
  script:
    - cd docker/backend
    - docker build -t $SPRING_IMAGE_NAME .
    - docker push $SPRING_IMAGE_NAME

# Frontend jobs
build-frontend:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run build --configuration=production
  artifacts:
    paths:
      - dist/

test-frontend:
  image: node:18-bullseye
  variables:
    CHROME_BIN: "/usr/bin/google-chrome-stable"
  before_script:
    - apt-get update && apt-get install -y wget gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - npm ci
    - npm install @angular/cli --save-dev
  script:
    - npx ng version
    - npx ng test --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
  artifacts:
    paths:
      - coverage/
    reports:
      junit:
        - coverage/junit.xml


docker-frontend:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo $GOOGLE_CLOUD_KEY > /tmp/google-cloud-key.json
    - gcloud auth activate-service-account --key-file /tmp/google-cloud-key.json
    - gcloud config set project $GOOGLE_PROJECT_ID
    - gcloud auth configure-docker
  script:
    - cd docker/frontend
    - docker build -t $ANGULAR_IMAGE_NAME .
    - docker push $ANGULAR_IMAGE_NAME

deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GOOGLE_CLOUD_KEY > /tmp/google-cloud-key.json
    - gcloud auth activate-service-account --key-file /tmp/google-cloud-key.json
    - gcloud config set project $GOOGLE_PROJECT_ID
    - gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
    - gcloud run deploy spring-backend --image $SPRING_IMAGE_NAME --platform managed --region europe-west1 --allow-unauthenticated
    - gcloud run deploy angular-frontend --image $ANGULAR_IMAGE_NAME --platform managed --region europe-west1 --allow-unauthenticated