name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOOGLE_PROJECT_ID: "peak-lattice-447302-b9"
  GOOGLE_COMPUTE_ZONE: "europe-west1-b"
  SPRING_IMAGE_NAME: "gcr.io/peak-lattice-447302-b9/spring-backend"
  ANGULAR_IMAGE_NAME: "gcr.io/peak-lattice-447302-b9/angular-frontend"

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: 'maven'
      
      - name: Build with Maven
        run: |
          cd src/app/Backend
          mvn clean package -DskipTests
      
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: src/app/Backend/target/*.jar

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: 'maven'
      
      - name: Test with Maven
        run: |
          cd src/app/Backend
          mvn test -X
      
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: src/app/Backend/target/surefire-reports/

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build --configuration=production
      
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Create test environment
        run: |
          mkdir -p src/assets
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: |
          npm run test -- \
            --no-watch \
            --no-progress \
            --browsers=ChromeHeadless \
            --karma-config=karma.conf.js

  docker-backend:
    needs: [build-backend, test-backend]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: src/app/Backend/target/
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY }}

      - name: Configure docker auth
        run: |
          gcloud auth configure-docker gcr.io --quiet
          
      - name: Build and push
        run: |
          IMAGE_TAG="${{ env.SPRING_IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG -f docker/backend/Dockerfile .
          docker push $IMAGE_TAG

  docker-frontend:
    needs: [build-frontend, test-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download frontend dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist/
          
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'
          token_format: 'access_token'
          
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          
      - name: Build and push
        run: |
          IMAGE_TAG="${{ env.ANGULAR_IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG -f docker/frontend/Dockerfile .
          docker push $IMAGE_TAG

  deploy:
    needs: [docker-backend, docker-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy spring-backend \
            --image ${{ env.SPRING_IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
            
          gcloud run deploy angular-frontend \
            --image ${{ env.ANGULAR_IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated